// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5091/' | (string & {});
};

export type AccessTokenResponse = {
    tokenType?: null | string;
    accessToken: string;
    expiresIn: number | string;
    refreshToken: string;
};

export type AssignOwnerToFractionRequest = {
    ownerId: number | string;
    isPrincipal: boolean;
};

export type CondominiumAdminDto = {
    userId: string;
    email: string;
};

export type CondominiumDto = {
    id: number | string;
    name: string;
    address: string;
    nif: string;
    iban: string;
    admins: Array<CondominiumAdminDto>;
};

export type CreateCondominiumRequest = {
    name: string;
    address: string;
    nif: string;
    iban: string;
};

export type CreateFractionRequest = {
    condominiumId: number | string;
    block: null | string;
    floor: string;
    letter: string;
    permilage: number | string;
};

export type CreateLedgerEntryRequest = {
    fractionId: number | string;
    principalOwnerId: number | string;
    type: LedgerEntryType;
    amount: number | string;
    dueDate: string;
};

export type CreateOwnerRequest = {
    name: string;
    nif: string;
    email: string;
    contact: string;
};

export type CreateQuotaConfigRequest = {
    fractionId: number | string;
    monthlyValue: number | string;
    startDate: string;
    endDate: null | string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type FractionDto = {
    id: number | string;
    condominiumId: number | string;
    block: null | string;
    floor: string;
    letter: string;
    permilage: number | string;
    paymentStatus: string;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type InfoRequest = {
    newEmail?: null | string;
    newPassword?: null | string;
    oldPassword?: null | string;
};

export type InfoResponse = {
    email: string;
    isEmailConfirmed: boolean;
};

export type LedgerEntryDto = {
    id: number | string;
    fractionId: number | string;
    principalOwnerId: number | string;
    principalOwnerName: string;
    type: string;
    amount: number | string;
    dueDate: string;
    status: string;
};

export type LedgerEntryStatus = number;

export type LedgerEntryType = number;

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: null | string;
    twoFactorRecoveryCode?: null | string;
};

export type OwnerDto = {
    id: number | string;
    name: string;
    nif: string;
    email: string;
    contact: string;
};

export type OwnerFractionDto = {
    ownerId: number | string;
    ownerName: string;
    fractionId: number | string;
    isPrincipal: boolean;
};

export type QuotaConfigDto = {
    id: number | string;
    fractionId: number | string;
    monthlyValue: number | string;
    startDate: string;
    endDate: null | string;
    isActive: boolean;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type ResendConfirmationEmailRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type TwoFactorRequest = {
    enable?: null | boolean;
    twoFactorCode?: null | string;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string;
    recoveryCodesLeft: number | string;
    recoveryCodes?: null | Array<string>;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type UpdateCondominiumRequest = {
    name: string;
    address: string;
    nif: string;
    iban: string;
};

export type UpdateFractionRequest = {
    block: null | string;
    floor: string;
    letter: string;
    permilage: number | string;
};

export type UpdateLedgerEntryStatusRequest = {
    status: LedgerEntryStatus;
};

export type UpdateOwnerRequest = {
    name: string;
    nif: string;
    email: string;
    contact: string;
};

export type UpdateQuotaConfigRequest = {
    monthlyValue: number | string;
    startDate: string;
    endDate: null | string;
    isActive: boolean;
};

export type PostAccountRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/account/register';
};

export type PostAccountRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostAccountRegisterError = PostAccountRegisterErrors[keyof PostAccountRegisterErrors];

export type PostAccountRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/account/login';
};

export type PostAccountLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostAccountLoginResponse = PostAccountLoginResponses[keyof PostAccountLoginResponses];

export type PostAccountRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/account/refresh';
};

export type PostAccountRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostAccountRefreshResponse = PostAccountRefreshResponses[keyof PostAccountRefreshResponses];

export type MapIdentityApiAccountConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/account/confirmEmail';
};

export type MapIdentityApiAccountConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/account/resendConfirmationEmail';
};

export type PostAccountResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/account/forgotPassword';
};

export type PostAccountForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostAccountForgotPasswordError = PostAccountForgotPasswordErrors[keyof PostAccountForgotPasswordErrors];

export type PostAccountForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/account/resetPassword';
};

export type PostAccountResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostAccountResetPasswordError = PostAccountResetPasswordErrors[keyof PostAccountResetPasswordErrors];

export type PostAccountResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAccountManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/account/manage/2fa';
};

export type PostAccountManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostAccountManage2FaError = PostAccountManage2FaErrors[keyof PostAccountManage2FaErrors];

export type PostAccountManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostAccountManage2FaResponse = PostAccountManage2FaResponses[keyof PostAccountManage2FaResponses];

export type GetAccountManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/manage/info';
};

export type GetAccountManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetAccountManageInfoError = GetAccountManageInfoErrors[keyof GetAccountManageInfoErrors];

export type GetAccountManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetAccountManageInfoResponse = GetAccountManageInfoResponses[keyof GetAccountManageInfoResponses];

export type PostAccountManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/account/manage/info';
};

export type PostAccountManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostAccountManageInfoError = PostAccountManageInfoErrors[keyof PostAccountManageInfoErrors];

export type PostAccountManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostAccountManageInfoResponse = PostAccountManageInfoResponses[keyof PostAccountManageInfoResponses];

export type GetApiCondominiumsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Condominiums';
};

export type GetApiCondominiumsResponses = {
    /**
     * OK
     */
    200: Array<CondominiumDto>;
};

export type GetApiCondominiumsResponse = GetApiCondominiumsResponses[keyof GetApiCondominiumsResponses];

export type PostApiCondominiumsData = {
    body: CreateCondominiumRequest;
    path?: never;
    query?: never;
    url: '/api/Condominiums';
};

export type PostApiCondominiumsResponses = {
    /**
     * OK
     */
    200: CondominiumDto;
};

export type PostApiCondominiumsResponse = PostApiCondominiumsResponses[keyof PostApiCondominiumsResponses];

export type DeleteApiCondominiumsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Condominiums/{id}';
};

export type DeleteApiCondominiumsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCondominiumsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Condominiums/{id}';
};

export type GetApiCondominiumsByIdResponses = {
    /**
     * OK
     */
    200: CondominiumDto;
};

export type GetApiCondominiumsByIdResponse = GetApiCondominiumsByIdResponses[keyof GetApiCondominiumsByIdResponses];

export type PutApiCondominiumsByIdData = {
    body: UpdateCondominiumRequest;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Condominiums/{id}';
};

export type PutApiCondominiumsByIdResponses = {
    /**
     * OK
     */
    200: CondominiumDto;
};

export type PutApiCondominiumsByIdResponse = PutApiCondominiumsByIdResponses[keyof PutApiCondominiumsByIdResponses];

export type DeleteApiCondominiumsByIdAdminsByUserIdData = {
    body?: never;
    path: {
        id: number | string;
        userId: string;
    };
    query?: never;
    url: '/api/Condominiums/{id}/admins/{userId}';
};

export type DeleteApiCondominiumsByIdAdminsByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiCondominiumsByIdAdminsByUserIdData = {
    body?: never;
    path: {
        id: number | string;
        userId: string;
    };
    query?: never;
    url: '/api/Condominiums/{id}/admins/{userId}';
};

export type PostApiCondominiumsByIdAdminsByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiFractionsData = {
    body?: never;
    path?: never;
    query?: {
        condominiumId?: number | string;
    };
    url: '/api/Fractions';
};

export type GetApiFractionsResponses = {
    /**
     * OK
     */
    200: Array<FractionDto>;
};

export type GetApiFractionsResponse = GetApiFractionsResponses[keyof GetApiFractionsResponses];

export type PostApiFractionsData = {
    body: CreateFractionRequest;
    path?: never;
    query?: never;
    url: '/api/Fractions';
};

export type PostApiFractionsResponses = {
    /**
     * OK
     */
    200: FractionDto;
};

export type PostApiFractionsResponse = PostApiFractionsResponses[keyof PostApiFractionsResponses];

export type DeleteApiFractionsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Fractions/{id}';
};

export type DeleteApiFractionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiFractionsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Fractions/{id}';
};

export type GetApiFractionsByIdResponses = {
    /**
     * OK
     */
    200: FractionDto;
};

export type GetApiFractionsByIdResponse = GetApiFractionsByIdResponses[keyof GetApiFractionsByIdResponses];

export type PutApiFractionsByIdData = {
    body: UpdateFractionRequest;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Fractions/{id}';
};

export type PutApiFractionsByIdResponses = {
    /**
     * OK
     */
    200: FractionDto;
};

export type PutApiFractionsByIdResponse = PutApiFractionsByIdResponses[keyof PutApiFractionsByIdResponses];

export type GetApiFractionsByIdOwnersData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Fractions/{id}/owners';
};

export type GetApiFractionsByIdOwnersResponses = {
    /**
     * OK
     */
    200: Array<OwnerFractionDto>;
};

export type GetApiFractionsByIdOwnersResponse = GetApiFractionsByIdOwnersResponses[keyof GetApiFractionsByIdOwnersResponses];

export type PostApiFractionsByIdOwnersData = {
    body: AssignOwnerToFractionRequest;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Fractions/{id}/owners';
};

export type PostApiFractionsByIdOwnersResponses = {
    /**
     * OK
     */
    200: OwnerFractionDto;
};

export type PostApiFractionsByIdOwnersResponse = PostApiFractionsByIdOwnersResponses[keyof PostApiFractionsByIdOwnersResponses];

export type DeleteApiFractionsByIdOwnersByOwnerIdData = {
    body?: never;
    path: {
        id: number | string;
        ownerId: number | string;
    };
    query?: never;
    url: '/api/Fractions/{id}/owners/{ownerId}';
};

export type DeleteApiFractionsByIdOwnersByOwnerIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLedgerEntriesData = {
    body?: never;
    path?: never;
    query?: {
        fractionId?: number | string;
        status?: LedgerEntryStatus;
    };
    url: '/api/LedgerEntries';
};

export type GetApiLedgerEntriesResponses = {
    /**
     * OK
     */
    200: Array<LedgerEntryDto>;
};

export type GetApiLedgerEntriesResponse = GetApiLedgerEntriesResponses[keyof GetApiLedgerEntriesResponses];

export type PostApiLedgerEntriesData = {
    body: CreateLedgerEntryRequest;
    path?: never;
    query?: never;
    url: '/api/LedgerEntries';
};

export type PostApiLedgerEntriesResponses = {
    /**
     * OK
     */
    200: LedgerEntryDto;
};

export type PostApiLedgerEntriesResponse = PostApiLedgerEntriesResponses[keyof PostApiLedgerEntriesResponses];

export type DeleteApiLedgerEntriesByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/LedgerEntries/{id}';
};

export type DeleteApiLedgerEntriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLedgerEntriesByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/LedgerEntries/{id}';
};

export type GetApiLedgerEntriesByIdResponses = {
    /**
     * OK
     */
    200: LedgerEntryDto;
};

export type GetApiLedgerEntriesByIdResponse = GetApiLedgerEntriesByIdResponses[keyof GetApiLedgerEntriesByIdResponses];

export type PatchApiLedgerEntriesByIdStatusData = {
    body: UpdateLedgerEntryStatusRequest;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/LedgerEntries/{id}/status';
};

export type PatchApiLedgerEntriesByIdStatusResponses = {
    /**
     * OK
     */
    200: LedgerEntryDto;
};

export type PatchApiLedgerEntriesByIdStatusResponse = PatchApiLedgerEntriesByIdStatusResponses[keyof PatchApiLedgerEntriesByIdStatusResponses];

export type GetApiOwnersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Owners';
};

export type GetApiOwnersResponses = {
    /**
     * OK
     */
    200: Array<OwnerDto>;
};

export type GetApiOwnersResponse = GetApiOwnersResponses[keyof GetApiOwnersResponses];

export type PostApiOwnersData = {
    body: CreateOwnerRequest;
    path?: never;
    query?: never;
    url: '/api/Owners';
};

export type PostApiOwnersResponses = {
    /**
     * OK
     */
    200: OwnerDto;
};

export type PostApiOwnersResponse = PostApiOwnersResponses[keyof PostApiOwnersResponses];

export type DeleteApiOwnersByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Owners/{id}';
};

export type DeleteApiOwnersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiOwnersByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Owners/{id}';
};

export type GetApiOwnersByIdResponses = {
    /**
     * OK
     */
    200: OwnerDto;
};

export type GetApiOwnersByIdResponse = GetApiOwnersByIdResponses[keyof GetApiOwnersByIdResponses];

export type PutApiOwnersByIdData = {
    body: UpdateOwnerRequest;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Owners/{id}';
};

export type PutApiOwnersByIdResponses = {
    /**
     * OK
     */
    200: OwnerDto;
};

export type PutApiOwnersByIdResponse = PutApiOwnersByIdResponses[keyof PutApiOwnersByIdResponses];

export type GetApiQuotaConfigsData = {
    body?: never;
    path?: never;
    query?: {
        fractionId?: number | string;
    };
    url: '/api/QuotaConfigs';
};

export type GetApiQuotaConfigsResponses = {
    /**
     * OK
     */
    200: Array<QuotaConfigDto>;
};

export type GetApiQuotaConfigsResponse = GetApiQuotaConfigsResponses[keyof GetApiQuotaConfigsResponses];

export type PostApiQuotaConfigsData = {
    body: CreateQuotaConfigRequest;
    path?: never;
    query?: never;
    url: '/api/QuotaConfigs';
};

export type PostApiQuotaConfigsResponses = {
    /**
     * OK
     */
    200: QuotaConfigDto;
};

export type PostApiQuotaConfigsResponse = PostApiQuotaConfigsResponses[keyof PostApiQuotaConfigsResponses];

export type DeleteApiQuotaConfigsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/QuotaConfigs/{id}';
};

export type DeleteApiQuotaConfigsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiQuotaConfigsByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/QuotaConfigs/{id}';
};

export type GetApiQuotaConfigsByIdResponses = {
    /**
     * OK
     */
    200: QuotaConfigDto;
};

export type GetApiQuotaConfigsByIdResponse = GetApiQuotaConfigsByIdResponses[keyof GetApiQuotaConfigsByIdResponses];

export type PutApiQuotaConfigsByIdData = {
    body: UpdateQuotaConfigRequest;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/QuotaConfigs/{id}';
};

export type PutApiQuotaConfigsByIdResponses = {
    /**
     * OK
     */
    200: QuotaConfigDto;
};

export type PutApiQuotaConfigsByIdResponse = PutApiQuotaConfigsByIdResponses[keyof PutApiQuotaConfigsByIdResponses];
