/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppOwnersIndexRouteImport } from './routes/_app/owners/index'
import { Route as AppLedgerIndexRouteImport } from './routes/_app/ledger/index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppCondominiumsIndexRouteImport } from './routes/_app/condominiums/index'
import { Route as AppFractionsFractionIdRouteImport } from './routes/_app/fractions/$fractionId'
import { Route as AppCondominiumsCondominiumIdRouteImport } from './routes/_app/condominiums/$condominiumId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnersIndexRoute = AppOwnersIndexRouteImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerIndexRoute = AppLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppCondominiumsIndexRoute = AppCondominiumsIndexRouteImport.update({
  id: '/condominiums/',
  path: '/condominiums/',
  getParentRoute: () => AppRoute,
} as any)
const AppFractionsFractionIdRoute = AppFractionsFractionIdRouteImport.update({
  id: '/fractions/$fractionId',
  path: '/fractions/$fractionId',
  getParentRoute: () => AppRoute,
} as any)
const AppCondominiumsCondominiumIdRoute =
  AppCondominiumsCondominiumIdRouteImport.update({
    id: '/condominiums/$condominiumId',
    path: '/condominiums/$condominiumId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/condominiums/$condominiumId': typeof AppCondominiumsCondominiumIdRoute
  '/fractions/$fractionId': typeof AppFractionsFractionIdRoute
  '/condominiums/': typeof AppCondominiumsIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/ledger/': typeof AppLedgerIndexRoute
  '/owners/': typeof AppOwnersIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/condominiums/$condominiumId': typeof AppCondominiumsCondominiumIdRoute
  '/fractions/$fractionId': typeof AppFractionsFractionIdRoute
  '/condominiums': typeof AppCondominiumsIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/ledger': typeof AppLedgerIndexRoute
  '/owners': typeof AppOwnersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/condominiums/$condominiumId': typeof AppCondominiumsCondominiumIdRoute
  '/_app/fractions/$fractionId': typeof AppFractionsFractionIdRoute
  '/_app/condominiums/': typeof AppCondominiumsIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/ledger/': typeof AppLedgerIndexRoute
  '/_app/owners/': typeof AppOwnersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/condominiums/$condominiumId'
    | '/fractions/$fractionId'
    | '/condominiums/'
    | '/expenses/'
    | '/ledger/'
    | '/owners/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/condominiums/$condominiumId'
    | '/fractions/$fractionId'
    | '/condominiums'
    | '/expenses'
    | '/ledger'
    | '/owners'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_app/condominiums/$condominiumId'
    | '/_app/fractions/$fractionId'
    | '/_app/condominiums/'
    | '/_app/expenses/'
    | '/_app/ledger/'
    | '/_app/owners/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owners/': {
      id: '/_app/owners/'
      path: '/owners'
      fullPath: '/owners/'
      preLoaderRoute: typeof AppOwnersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger/': {
      id: '/_app/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AppLedgerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/condominiums/': {
      id: '/_app/condominiums/'
      path: '/condominiums'
      fullPath: '/condominiums/'
      preLoaderRoute: typeof AppCondominiumsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fractions/$fractionId': {
      id: '/_app/fractions/$fractionId'
      path: '/fractions/$fractionId'
      fullPath: '/fractions/$fractionId'
      preLoaderRoute: typeof AppFractionsFractionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/condominiums/$condominiumId': {
      id: '/_app/condominiums/$condominiumId'
      path: '/condominiums/$condominiumId'
      fullPath: '/condominiums/$condominiumId'
      preLoaderRoute: typeof AppCondominiumsCondominiumIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppCondominiumsCondominiumIdRoute: typeof AppCondominiumsCondominiumIdRoute
  AppFractionsFractionIdRoute: typeof AppFractionsFractionIdRoute
  AppCondominiumsIndexRoute: typeof AppCondominiumsIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppLedgerIndexRoute: typeof AppLedgerIndexRoute
  AppOwnersIndexRoute: typeof AppOwnersIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppCondominiumsCondominiumIdRoute: AppCondominiumsCondominiumIdRoute,
  AppFractionsFractionIdRoute: AppFractionsFractionIdRoute,
  AppCondominiumsIndexRoute: AppCondominiumsIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppLedgerIndexRoute: AppLedgerIndexRoute,
  AppOwnersIndexRoute: AppOwnersIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
